version: "3.8"
services: 
  api:
    # image: post-nest-app
    build: 
      dockerfile: Dockerfile
      context: .
    depends_on:
      - postgres
    environment: 
      DATABASE_URL: postgres://user:password@postgres:5432/db
    
    ports:
      - "8080:8080"
    
  postgres: 
    image: postgres:16.1
    ports:
      - "35000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db